version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: mav-bittrack_server_1
      APP_PORT: 8585
  server:
    image: ghcr.io/maverick-2009/bittrack:1.0.0@sha256:7c5e8b3f7425ce995606c934656aedbf8e393824e5ffef55846ec424e9ea473f
    init: true
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/data:/app/data
    environment:
      DATA_DIR: "/app/data"
      TOR_PROXY_HOST: tor_proxy
      TOR_PROXY_PORT: "9050"
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "umbrel.local:host-gateway"
    networks:
      - default
      - umbrel_main_network

networks:
  umbrel_main_network:
    external: true
