version: "3.7"
services:
  app_proxy:
    environment:
      APP_HOST: mav-bittrack_server_1
      APP_PORT: 8585

  server:
    image: ghcr.io/maverick-2009/bittrack:1.0.0@sha256:15feda63da92e5b3cf0069428fd2621e5c33d9df061040c224872e17d0e2bbf5
    init: true
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/data:/app/data
    environment:
      DATA_DIR: "/app/data"
    extra_hosts:
      - "host.docker.internal:host-gateway"
